title: Harsh Thakur 
description: > 
  <br>People often call me tech savvy. <br>
  <br>Started my journey as a security enthusiast and now moving towards Devops related technology.  <br>
  <a href="https://www.linkedin.com/in/harsh-thakur-499096158/">View My LinkedIn Profile</a>

theme: jekyll-theme-cayman

