title: Harsh Thakur 
description: > 
  <br>People often call me tech savvy. <br>
  <br>Started my journey as a security enthusiast and now, I'm a DevOps Engineer.  <br>

theme: jekyll-theme-architect

